In [31]:
import pandas as pd
import numpy as np

In [32]:
data=pd.read_csv("Test.csv")
df=pd.DataFrame(data)
df

,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Var_1,Segmentation
0,458989,Female,Yes,36,Yes,Engineer,0.0,Low,1.0,Cat_6,B
1,458994,Male,Yes,37,Yes,Healthcare,8.0,Average,4.0,Cat_6,A
2,458996,Female,Yes,69,No,NaN,0.0,Low,1.0,Cat_6,A
3,459000,Male,Yes,59,No,Executive,11.0,High,2.0,Cat_6,B
4,459001,Female,No,19,No,Marketing,NaN,Low,4.0,Cat_6,A
...,...,...,...,...,...,...,...,...,...,...,...
2622,467954,Male,No,29,No,Healthcare,9.0,Low,4.0,Cat_6,B
2623,467958,Female,No,35,Yes,Doctor,1.0,Low,1.0,Cat_6,A
2624,467960,Female,No,53,Yes,Entertainment,NaN,Low,2.0,Cat_6,C
2625,467961,Male,Yes,47,Yes,Executive,1.0,High,5.0,Cat_4,C
2626,467968,Female,No,43,Yes,Healthcare,9.0,Low,3.0,Cat_7,A

In [33]:
# Replace Yes -> 1 and No -> 0  in Ever_Married column
df["Ever_Married"]=df["Ever_Married"].map({"Yes":1,"No":0})
df["Ever_Married"]

0       1.0
1       1.0
2       1.0
3       1.0
4       0.0
       ...
2622    0.0
2623    0.0
2624    0.0
2625    1.0
2626    0.0
Name: Ever_Married, Length: 2627, dtype: float64

In [34]:
# Replace Male -> M and Female -> F in gender column

df["Gender"]=df["Gender"].map({"Male":"M","Female":"F"})
df

,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Var_1,Segmentation
0,458989,F,1.0,36,Yes,Engineer,0.0,Low,1.0,Cat_6,B
1,458994,M,1.0,37,Yes,Healthcare,8.0,Average,4.0,Cat_6,A
2,458996,F,1.0,69,No,NaN,0.0,Low,1.0,Cat_6,A
3,459000,M,1.0,59,No,Executive,11.0,High,2.0,Cat_6,B
4,459001,F,0.0,19,No,Marketing,NaN,Low,4.0,Cat_6,A
...,...,...,...,...,...,...,...,...,...,...,...
2622,467954,M,0.0,29,No,Healthcare,9.0,Low,4.0,Cat_6,B
2623,467958,F,0.0,35,Yes,Doctor,1.0,Low,1.0,Cat_6,A
2624,467960,F,0.0,53,Yes,Entertainment,NaN,Low,2.0,Cat_6,C
2625,467961,M,1.0,47,Yes,Executive,1.0,High,5.0,Cat_4,C
2626,467968,F,0.0,43,Yes,Healthcare,9.0,Low,3.0,Cat_7,A

In [35]:
# Replace low,average,high in spending with 1,2,3 respectively

df["Spending_Score"]=df["Spending_Score"].map({"Low":1,"Average":2,"High":3})
df

,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Var_1,Segmentation
0,458989,F,1.0,36,Yes,Engineer,0.0,1,1.0,Cat_6,B
1,458994,M,1.0,37,Yes,Healthcare,8.0,2,4.0,Cat_6,A
2,458996,F,1.0,69,No,NaN,0.0,1,1.0,Cat_6,A
3,459000,M,1.0,59,No,Executive,11.0,3,2.0,Cat_6,B
4,459001,F,0.0,19,No,Marketing,NaN,1,4.0,Cat_6,A
...,...,...,...,...,...,...,...,...,...,...,...
2622,467954,M,0.0,29,No,Healthcare,9.0,1,4.0,Cat_6,B
2623,467958,F,0.0,35,Yes,Doctor,1.0,1,1.0,Cat_6,A
2624,467960,F,0.0,53,Yes,Entertainment,NaN,1,2.0,Cat_6,C
2625,467961,M,1.0,47,Yes,Executive,1.0,3,5.0,Cat_4,C
2626,467968,F,0.0,43,Yes,Healthcare,9.0,1,3.0,Cat_7,A

In [36]:
df["Work_Experience"].isna().sum()
df["Work_Experience"]=df["Work_Experience"].fillna(0)
df

,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Var_1,Segmentation
0,458989,F,1.0,36,Yes,Engineer,0.0,1,1.0,Cat_6,B
1,458994,M,1.0,37,Yes,Healthcare,8.0,2,4.0,Cat_6,A
2,458996,F,1.0,69,No,NaN,0.0,1,1.0,Cat_6,A
3,459000,M,1.0,59,No,Executive,11.0,3,2.0,Cat_6,B
4,459001,F,0.0,19,No,Marketing,0.0,1,4.0,Cat_6,A
...,...,...,...,...,...,...,...,...,...,...,...
2622,467954,M,0.0,29,No,Healthcare,9.0,1,4.0,Cat_6,B
2623,467958,F,0.0,35,Yes,Doctor,1.0,1,1.0,Cat_6,A
2624,467960,F,0.0,53,Yes,Entertainment,0.0,1,2.0,Cat_6,C
2625,467961,M,1.0,47,Yes,Executive,1.0,3,5.0,Cat_4,C
2626,467968,F,0.0,43,Yes,Healthcare,9.0,1,3.0,Cat_7,A

In [37]:
# replace all value in var_1=cat_6 with category_6

df["Var_1"]=df["Var_1"].replace({"Cat_6":"Category_6"})
df

,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Var_1,Segmentation
0,458989,F,1.0,36,Yes,Engineer,0.0,1,1.0,Category_6,B
1,458994,M,1.0,37,Yes,Healthcare,8.0,2,4.0,Category_6,A
2,458996,F,1.0,69,No,NaN,0.0,1,1.0,Category_6,A
3,459000,M,1.0,59,No,Executive,11.0,3,2.0,Category_6,B
4,459001,F,0.0,19,No,Marketing,0.0,1,4.0,Category_6,A
...,...,...,...,...,...,...,...,...,...,...,...
2622,467954,M,0.0,29,No,Healthcare,9.0,1,4.0,Category_6,B
2623,467958,F,0.0,35,Yes,Doctor,1.0,1,1.0,Category_6,A
2624,467960,F,0.0,53,Yes,Entertainment,0.0,1,2.0,Category_6,C
2625,467961,M,1.0,47,Yes,Executive,1.0,3,5.0,Cat_4,C
2626,467968,F,0.0,43,Yes,Healthcare,9.0,1,3.0,Cat_7,A

In [38]:
# Replace age values greater than 80 with mean of age value


mean_value=df["Age"].mean()
df["Age"]=df["Age"].apply(lambda a:mean_value if a>80 else a)
df["Age"]

0       36.0
1       37.0
2       69.0
3       59.0
4       19.0
        ...
2622    29.0
2623    35.0
2624    53.0
2625    47.0
2626    43.0
Name: Age, Length: 2627, dtype: float64

In [39]:
# Replace doctor profession with medical

df["Profession"]=df["Profession"].replace({"Doctor":"Medical"})
df

,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Var_1,Segmentation
0,458989,F,1.0,36.0,Yes,Engineer,0.0,1,1.0,Category_6,B
1,458994,M,1.0,37.0,Yes,Healthcare,8.0,2,4.0,Category_6,A
2,458996,F,1.0,69.0,No,NaN,0.0,1,1.0,Category_6,A
3,459000,M,1.0,59.0,No,Executive,11.0,3,2.0,Category_6,B
4,459001,F,0.0,19.0,No,Marketing,0.0,1,4.0,Category_6,A
...,...,...,...,...,...,...,...,...,...,...,...
2622,467954,M,0.0,29.0,No,Healthcare,9.0,1,4.0,Category_6,B
2623,467958,F,0.0,35.0,Yes,Medical,1.0,1,1.0,Category_6,A
2624,467960,F,0.0,53.0,Yes,Entertainment,0.0,1,2.0,Category_6,C
2625,467961,M,1.0,47.0,Yes,Executive,1.0,3,5.0,Cat_4,C
2626,467968,F,0.0,43.0,Yes,Healthcare,9.0,1,3.0,Cat_7,A

In [40]:
# replace segemntation labels (a,b,c,d) with numerical values

df["Segmentation"]=df["Segmentation"].replace({"A":1,"B":2,"C":3,"D":4})
df

C:\Users\HP\AppData\Local\Temp\ipykernel_12596\1017269159.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Segmentation"]=df["Segmentation"].replace({"A":1,"B":2,"C":3,"D":4})

,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Var_1,Segmentation
0,458989,F,1.0,36.0,Yes,Engineer,0.0,1,1.0,Category_6,2
1,458994,M,1.0,37.0,Yes,Healthcare,8.0,2,4.0,Category_6,1
2,458996,F,1.0,69.0,No,NaN,0.0,1,1.0,Category_6,1
3,459000,M,1.0,59.0,No,Executive,11.0,3,2.0,Category_6,2
4,459001,F,0.0,19.0,No,Marketing,0.0,1,4.0,Category_6,1
...,...,...,...,...,...,...,...,...,...,...,...
2622,467954,M,0.0,29.0,No,Healthcare,9.0,1,4.0,Category_6,2
2623,467958,F,0.0,35.0,Yes,Medical,1.0,1,1.0,Category_6,1
2624,467960,F,0.0,53.0,Yes,Entertainment,0.0,1,2.0,Category_6,3
2625,467961,M,1.0,47.0,Yes,Executive,1.0,3,5.0,Cat_4,3
2626,467968,F,0.0,43.0,Yes,Healthcare,9.0,1,3.0,Cat_7,1

In [42]:
# Find how many missing values are present in each columns
df.isna().sum()

ID                   0
Gender               0
Ever_Married        50
Age                  0
Graduated           24
Profession          38
Work_Experience      0
Spending_Score       0
Family_Size        113
Var_1               32
Segmentation         0
dtype: int64

In [43]:
# drop rows where graduated is missing

df=df.dropna(subset=["Graduated"])
df.isna().sum()

ID                   0
Gender               0
Ever_Married        49
Age                  0
Graduated            0
Profession          37
Work_Experience      0
Spending_Score       0
Family_Size        112
Var_1               32
Segmentation         0
dtype: int64

In [44]:
# Fill the missing values in profession with "Unknown"
df["Profession"]=df["Profession"].fillna("Unknown")
df

C:\Users\HP\AppData\Local\Temp\ipykernel_12596\1061615289.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Profession"]=df["Profession"].fillna("Unknown")

,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Var_1,Segmentation
0,458989,F,1.0,36.0,Yes,Engineer,0.0,1,1.0,Category_6,2
1,458994,M,1.0,37.0,Yes,Healthcare,8.0,2,4.0,Category_6,1
2,458996,F,1.0,69.0,No,Unknown,0.0,1,1.0,Category_6,1
3,459000,M,1.0,59.0,No,Executive,11.0,3,2.0,Category_6,2
4,459001,F,0.0,19.0,No,Marketing,0.0,1,4.0,Category_6,1
...,...,...,...,...,...,...,...,...,...,...,...
2622,467954,M,0.0,29.0,No,Healthcare,9.0,1,4.0,Category_6,2
2623,467958,F,0.0,35.0,Yes,Medical,1.0,1,1.0,Category_6,1
2624,467960,F,0.0,53.0,Yes,Entertainment,0.0,1,2.0,Category_6,3
2625,467961,M,1.0,47.0,Yes,Executive,1.0,3,5.0,Cat_4,3
2626,467968,F,0.0,43.0,Yes,Healthcare,9.0,1,3.0,Cat_7,1

In [45]:
# remove rows where age is less than 18

df=df.loc[df["Age"]>18,:]
df

,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Var_1,Segmentation
0,458989,F,1.0,36.0,Yes,Engineer,0.0,1,1.0,Category_6,2
1,458994,M,1.0,37.0,Yes,Healthcare,8.0,2,4.0,Category_6,1
2,458996,F,1.0,69.0,No,Unknown,0.0,1,1.0,Category_6,1
3,459000,M,1.0,59.0,No,Executive,11.0,3,2.0,Category_6,2
4,459001,F,0.0,19.0,No,Marketing,0.0,1,4.0,Category_6,1
...,...,...,...,...,...,...,...,...,...,...,...
2622,467954,M,0.0,29.0,No,Healthcare,9.0,1,4.0,Category_6,2
2623,467958,F,0.0,35.0,Yes,Medical,1.0,1,1.0,Category_6,1
2624,467960,F,0.0,53.0,Yes,Entertainment,0.0,1,2.0,Category_6,3
2625,467961,M,1.0,47.0,Yes,Executive,1.0,3,5.0,Cat_4,3
2626,467968,F,0.0,43.0,Yes,Healthcare,9.0,1,3.0,Cat_7,1

In [47]:
# identify duplicate rows based on id and remove them

df=df.drop_duplicates(subset=["ID"],keep="first")
df.duplicated(subset=["ID"]).sum()

np.int64(0)

In [ ]:
# Display all customers whose spending is "High" (We have converted high to 3 in earlier question)

df.loc[df["Spending_Score"]==3]

,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Var_1,Segmentation
3,459000,M,1.0,59.0,No,Executive,11.0,3,2.0,Category_6,2
5,459003,M,1.0,47.0,Yes,Medical,0.0,3,5.0,Cat_4,3
20,459056,M,1.0,63.0,No,Executive,0.0,3,3.0,Category_6,1
21,459057,M,1.0,69.0,No,Lawyer,0.0,3,NaN,Category_6,4
23,459059,M,1.0,79.0,No,Executive,0.0,3,2.0,Category_6,2
...,...,...,...,...,...,...,...,...,...,...,...
2591,467868,F,1.0,66.0,Yes,Entertainment,0.0,3,2.0,Category_6,1
2592,467876,F,1.0,50.0,Yes,Artist,9.0,3,2.0,Category_6,3
2593,467879,F,1.0,51.0,Yes,Artist,0.0,3,4.0,Category_6,1
2605,467905,M,1.0,37.0,Yes,Executive,0.0,3,3.0,Category_6,2
2625,467961,M,1.0,47.0,Yes,Executive,1.0,3,5.0,Cat_4,3

In [49]:
# Find all married people (Ever_Married=Yes) (we have converted Yes to 1 in earlier question)

df.loc[df["Ever_Married"]==1]

,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Var_1,Segmentation
0,458989,F,1.0,36.0,Yes,Engineer,0.0,1,1.0,Category_6,2
1,458994,M,1.0,37.0,Yes,Healthcare,8.0,2,4.0,Category_6,1
2,458996,F,1.0,69.0,No,Unknown,0.0,1,1.0,Category_6,1
3,459000,M,1.0,59.0,No,Executive,11.0,3,2.0,Category_6,2
5,459003,M,1.0,47.0,Yes,Medical,0.0,3,5.0,Cat_4,3
...,...,...,...,...,...,...,...,...,...,...,...
2611,467929,F,1.0,36.0,Yes,Artist,1.0,2,2.0,Category_6,3
2612,467930,M,1.0,45.0,Yes,Entertainment,4.0,2,2.0,Category_6,3
2616,467938,M,1.0,46.0,Yes,Entertainment,5.0,1,1.0,Cat_2,3
2618,467946,F,1.0,42.0,Yes,Artist,0.0,1,2.0,Category_6,1
2625,467961,M,1.0,47.0,Yes,Executive,1.0,3,5.0,Cat_4,3

In [50]:
# Show customers whose work_Experience is greater than 5 years

df.loc[df["Work_Experience"]>5]

,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Var_1,Segmentation
1,458994,M,1.0,37.0,Yes,Healthcare,8.0,2,4.0,Category_6,1
3,459000,M,1.0,59.0,No,Executive,11.0,3,2.0,Category_6,2
13,459026,M,0.0,27.0,No,Healthcare,8.0,1,3.0,Cat_3,4
18,459041,M,1.0,55.0,Yes,Artist,8.0,1,1.0,Category_6,2
24,459061,F,1.0,35.0,Yes,Healthcare,9.0,3,3.0,Category_6,2
...,...,...,...,...,...,...,...,...,...,...,...
2604,467904,F,0.0,31.0,Yes,Artist,14.0,1,1.0,Category_6,4
2610,467927,M,0.0,30.0,Yes,Medical,8.0,1,6.0,Cat_2,4
2617,467940,F,0.0,27.0,No,Marketing,8.0,1,4.0,Cat_2,4
2622,467954,M,0.0,29.0,No,Healthcare,9.0,1,4.0,Category_6,2
2626,467968,F,0.0,43.0,Yes,Healthcare,9.0,1,3.0,Cat_7,1

In [54]:
# Get customers aged between 30 and 50

df.loc[(df["Age"]>30)&(df["Age"]<50)]

,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Var_1,Segmentation
0,458989,F,1.0,36.0,Yes,Engineer,0.0,1,1.0,Category_6,2
1,458994,M,1.0,37.0,Yes,Healthcare,8.0,2,4.0,Category_6,1
5,459003,M,1.0,47.0,Yes,Medical,0.0,3,5.0,Cat_4,3
7,459008,F,1.0,47.0,Yes,Artist,1.0,2,3.0,Category_6,4
17,459039,M,1.0,45.0,Yes,Artist,1.0,2,2.0,Category_6,2
...,...,...,...,...,...,...,...,...,...,...,...
2618,467946,F,1.0,42.0,Yes,Artist,0.0,1,2.0,Category_6,1
2621,467950,F,0.0,35.0,Yes,Entertainment,1.0,1,2.0,Category_6,4
2623,467958,F,0.0,35.0,Yes,Medical,1.0,1,1.0,Category_6,1
2625,467961,M,1.0,47.0,Yes,Executive,1.0,3,5.0,Cat_4,3
2626,467968,F,0.0,43.0,Yes,Healthcare,9.0,1,3.0,Cat_7,1

In [55]:
# Show customers who are "Doctor" with "High" spending (We have converted "Doctor" to "Medical" and "High" to "3" in earlier questions)

df.loc[(df["Profession"]=="Medical")&(df["Spending_Score"]==3)]

,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Var_1,Segmentation
5,459003,M,1.0,47.0,Yes,Medical,0.0,3,5.0,Cat_4,3
134,459405,F,1.0,78.0,No,Medical,1.0,3,2.0,Category_6,2
507,460626,M,1.0,47.0,No,Medical,8.0,3,4.0,Category_6,4
1014,462381,F,1.0,48.0,No,Medical,1.0,3,2.0,Category_6,3
1086,462612,F,1.0,27.0,No,Medical,0.0,3,6.0,Cat_4,4
1163,462874,M,1.0,55.0,Yes,Medical,0.0,3,2.0,Category_6,2
1231,463118,F,1.0,50.0,Yes,Medical,0.0,3,3.0,Category_6,4
1318,463404,M,1.0,27.0,No,Medical,0.0,3,2.0,Cat_3,3
1518,464110,M,1.0,63.0,Yes,Medical,0.0,3,2.0,Category_6,3
2174,466395,F,1.0,39.0,Yes,Medical,3.0,3,2.0,Cat_4,1

In [56]:
# Create a new column "Age_Group" having 
#<30--Young
#30-50--Adult
#>50--Senior

df["Age_Group"]=df["Age"].apply(lambda a:"Young" if a<30 else "Adult" if a>=30 and a<=50 else "Senior")
df

,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Var_1,Segmentation,Age_Group
0,458989,F,1.0,36.0,Yes,Engineer,0.0,1,1.0,Category_6,2,Adult
1,458994,M,1.0,37.0,Yes,Healthcare,8.0,2,4.0,Category_6,1,Adult
2,458996,F,1.0,69.0,No,Unknown,0.0,1,1.0,Category_6,1,Senior
3,459000,M,1.0,59.0,No,Executive,11.0,3,2.0,Category_6,2,Senior
4,459001,F,0.0,19.0,No,Marketing,0.0,1,4.0,Category_6,1,Young
...,...,...,...,...,...,...,...,...,...,...,...,...
2622,467954,M,0.0,29.0,No,Healthcare,9.0,1,4.0,Category_6,2,Young
2623,467958,F,0.0,35.0,Yes,Medical,1.0,1,1.0,Category_6,1,Adult
2624,467960,F,0.0,53.0,Yes,Entertainment,0.0,1,2.0,Category_6,3,Senior
2625,467961,M,1.0,47.0,Yes,Executive,1.0,3,5.0,Cat_4,3,Adult
2626,467968,F,0.0,43.0,Yes,Healthcare,9.0,1,3.0,Cat_7,1,Adult

In [58]:
# sort the dataset by age (descending) and work_experience (Ascending)


df=df.sort_values(by="Age",ascending=False)
df=df.sort_values(by="Work_Experience",ascending=True)
df

,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Var_1,Segmentation,Age_Group
9,459014,M,0.0,19.0,No,Healthcare,0.0,1,4.0,Category_6,2,Young
2619,467948,F,0.0,19.0,No,Healthcare,0.0,1,3.0,Category_6,1,Young
2562,467740,M,0.0,19.0,No,Healthcare,0.0,1,3.0,Category_6,4,Young
359,460162,F,0.0,19.0,No,Healthcare,0.0,1,4.0,Cat_2,4,Young
360,460166,F,0.0,19.0,No,Healthcare,0.0,1,7.0,Cat_2,1,Young
...,...,...,...,...,...,...,...,...,...,...,...,...
1619,464522,F,0.0,39.0,Yes,Engineer,14.0,1,1.0,Category_6,3,Adult
893,461994,M,1.0,20.0,No,Medical,14.0,1,2.0,Category_6,2,Young
2060,466024,F,1.0,43.0,No,Entertainment,14.0,1,2.0,Cat_3,1,Adult
1551,464217,F,0.0,30.0,No,Healthcare,14.0,1,3.0,Category_6,1,Adult
403,460315,F,0.0,35.0,No,Medical,14.0,1,6.0,Cat_7,1,Adult

In [59]:
# sort the dataset by age (descending) and work_experience (Ascending)

df=df.sort_values(by=["Age","Work_Experience"],ascending=[False,True])
df

,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Var_1,Segmentation,Age_Group
50,459144,M,1.0,80.0,Yes,Lawyer,0.0,3,2.0,Category_6,2,Senior
975,462240,M,1.0,80.0,No,Lawyer,0.0,3,2.0,Category_6,1,Senior
2348,467058,M,1.0,80.0,No,Executive,0.0,3,2.0,Category_6,1,Senior
107,459338,M,1.0,80.0,No,Executive,0.0,1,NaN,Category_6,4,Senior
1841,465264,M,1.0,80.0,No,Executive,0.0,1,1.0,Category_6,4,Senior
...,...,...,...,...,...,...,...,...,...,...,...,...
649,461128,M,0.0,19.0,No,Healthcare,7.0,1,3.0,Category_6,3,Young
465,460485,F,0.0,19.0,No,Marketing,8.0,1,5.0,Cat_3,4,Young
637,461082,M,0.0,19.0,No,Healthcare,8.0,1,4.0,Cat_1,1,Young
1968,465689,M,0.0,19.0,No,Healthcare,8.0,1,4.0,Cat_3,1,Young
466,460489,M,0.0,19.0,No,Healthcare,9.0,1,6.0,Cat_3,4,Young