In [99]:
import pandas as pd
import numpy as np

In [100]:
data=pd.read_csv("Netflix TV Shows and Movies.csv")
df=pd.DataFrame(data)
df

,index,id,title,type,description,release_year,age_certification,runtime,imdb_id,imdb_score,imdb_votes
0,0,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,tt0075314,8.3,795222.0
1,1,tm127384,Monty Python and the Holy Grail,MOVIE,"King Arthur, accompanied by his squire, recrui...",1975,PG,91,tt0071853,8.2,530877.0
2,2,tm70993,Life of Brian,MOVIE,"Brian Cohen is an average young Jewish man, bu...",1979,R,94,tt0079470,8.0,392419.0
3,3,tm190788,The Exorcist,MOVIE,12-year-old Regan MacNeil begins to adapt an e...,1973,R,133,tt0070047,8.1,391942.0
4,4,ts22164,Monty Python's Flying Circus,SHOW,A British sketch comedy series with the shows ...,1969,TV-14,30,tt0063929,8.8,72895.0
...,...,...,...,...,...,...,...,...,...,...,...
5278,5278,tm1040816,Momshies! Your Soul is Mine,MOVIE,Three women with totally different lives accid...,2021,NaN,108,tt14412240,5.8,26.0
5279,5279,tm1014599,Fine Wine,MOVIE,A beautiful love story that can happen between...,2021,NaN,100,tt13857480,6.9,39.0
5280,5280,tm1045018,Clash,MOVIE,A man from Nigeria returns to his family in Ca...,2021,NaN,88,tt14620732,6.5,32.0
5281,5281,tm1098060,Shadow Parties,MOVIE,A family faces destruction in a long-running c...,2021,NaN,116,tt10168094,6.2,9.0
5282,5282,ts271048,Mighty Little Bheem: Kite Festival,SHOW,"With winter behind them, Bheem and his townspe...",2021,NaN,0,tt13711094,8.8,16.0

In [101]:
df.columns

Index(['index', 'id', 'title', 'type', 'description', 'release_year',
       'age_certification', 'runtime', 'imdb_id', 'imdb_score', 'imdb_votes'],
      dtype='object')

In [102]:
df=df.drop(columns=["index","id","title","description","release_year","imdb_id"],axis=1)
df

       type age_certification  runtime  imdb_score  imdb_votes
0     MOVIE                 R      113         8.3    795222.0
1     MOVIE                PG       91         8.2    530877.0
2     MOVIE                 R       94         8.0    392419.0
3     MOVIE                 R      133         8.1    391942.0
4      SHOW             TV-14       30         8.8     72895.0
...     ...               ...      ...         ...         ...
5278  MOVIE               NaN      108         5.8        26.0
5279  MOVIE               NaN      100         6.9        39.0
5280  MOVIE               NaN       88         6.5        32.0
5281  MOVIE               NaN      116         6.2         9.0
5282   SHOW               NaN        0         8.8        16.0

[5283 rows x 5 columns]

In [103]:
df.isna().sum()

type                    0
age_certification    2285
runtime                 0
imdb_score              0
imdb_votes             16
dtype: int64

In [104]:
df=df.drop(columns=["age_certification"],axis=1)
df

       type  runtime  imdb_score  imdb_votes
0     MOVIE      113         8.3    795222.0
1     MOVIE       91         8.2    530877.0
2     MOVIE       94         8.0    392419.0
3     MOVIE      133         8.1    391942.0
4      SHOW       30         8.8     72895.0
...     ...      ...         ...         ...
5278  MOVIE      108         5.8        26.0
5279  MOVIE      100         6.9        39.0
5280  MOVIE       88         6.5        32.0
5281  MOVIE      116         6.2         9.0
5282   SHOW        0         8.8        16.0

[5283 rows x 4 columns]

In [105]:
df.isna().sum()

type           0
runtime        0
imdb_score     0
imdb_votes    16
dtype: int64

In [106]:
df.dtypes

type           object
runtime         int64
imdb_score    float64
imdb_votes    float64
dtype: object

In [107]:
df["imdb_votes"]=df["imdb_votes"].fillna(df["imdb_votes"].mean())

In [108]:
df.isna().sum()

type          0
runtime       0
imdb_score    0
imdb_votes    0
dtype: int64

In [109]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

df["type"]=le.fit_transform(df["type"])

In [110]:
Y=df.iloc[:,2]
Y

0       8.3
1       8.2
2       8.0
3       8.1
4       8.8
       ...
5278    5.8
5279    6.9
5280    6.5
5281    6.2
5282    8.8
Name: imdb_score, Length: 5283, dtype: float64

In [111]:
df=df.drop(columns=["imdb_score"],axis=1)
X=df
X

      type  runtime  imdb_votes
0        0      113    795222.0
1        0       91    530877.0
2        0       94    392419.0
3        0      133    391942.0
4        1       30     72895.0
...    ...      ...         ...
5278     0      108        26.0
5279     0      100        39.0
5280     0       88        32.0
5281     0      116         9.0
5282     1        0        16.0

[5283 rows x 3 columns]

In [112]:
from sklearn.model_selection import train_test_split 

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3)

In [113]:
from sklearn.preprocessing import StandardScaler

sc=StandardScaler()

X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [114]:
from sklearn.linear_model import LinearRegression

lr=LinearRegression()

model=lr.fit(X_train,Y_train)
Y_pred=model.predict(X_test)
Y_pred

array([7.07078593, 6.41700023, 6.17198961, ..., 6.84007257, 7.03146646,
       6.91441346], shape=(1585,))

In [115]:
from sklearn.metrics import mean_absolute_percentage_error,r2_score

print(f"mean_absolute_percentage_error = {mean_absolute_percentage_error(Y_test,Y_pred)}")
print(f"R2_Score = {r2_score(Y_test,Y_pred)}")

mean_absolute_percentage_error = 0.14403191473331048
R2_Score = 0.150802235049613