In [1]:
import pandas as pd
import numpy as np
import re # This module provides pattern matching operations using list of strings given
import nltk

In [2]:
data=pd.read_csv("twitter_validation.csv",header=None)
df=pd.DataFrame(data)
df

,0,1,2,3
0,3364,Facebook,Irrelevant,I mentioned on Facebook that I was struggling ...
1,352,Amazon,Neutral,BBC News - Amazon boss Jeff Bezos rejects clai...
2,8312,Microsoft,Negative,@Microsoft Why do I pay for WORD when it funct...
3,4371,CS-GO,Negative,"CSGO matchmaking is so full of closet hacking,..."
4,4433,Google,Neutral,Now the President is slapping Americans in the...
...,...,...,...,...
995,4891,GrandTheftAuto(GTA),Irrelevant,⭐️ Toronto is the arts and culture capital of ...
996,4359,CS-GO,Irrelevant,tHIS IS ACTUALLY A GOOD MOVE TOT BRING MORE VI...
997,2652,Borderlands,Positive,Today sucked so it’s time to drink wine n play...
998,8069,Microsoft,Positive,Bought a fraction of Microsoft today. Small wins.
999,6960,johnson&johnson,Neutral,Johnson & Johnson to stop selling talc baby po...

In [3]:
df.columns=["ID","Platform","Nature","Comment"]
df

,ID,Platform,Nature,Comment
0,3364,Facebook,Irrelevant,I mentioned on Facebook that I was struggling ...
1,352,Amazon,Neutral,BBC News - Amazon boss Jeff Bezos rejects clai...
2,8312,Microsoft,Negative,@Microsoft Why do I pay for WORD when it funct...
3,4371,CS-GO,Negative,"CSGO matchmaking is so full of closet hacking,..."
4,4433,Google,Neutral,Now the President is slapping Americans in the...
...,...,...,...,...
995,4891,GrandTheftAuto(GTA),Irrelevant,⭐️ Toronto is the arts and culture capital of ...
996,4359,CS-GO,Irrelevant,tHIS IS ACTUALLY A GOOD MOVE TOT BRING MORE VI...
997,2652,Borderlands,Positive,Today sucked so it’s time to drink wine n play...
998,8069,Microsoft,Positive,Bought a fraction of Microsoft today. Small wins.
999,6960,johnson&johnson,Neutral,Johnson & Johnson to stop selling talc baby po...

In [4]:
df["Comment"]=df["Comment"].str.lower()
df["Comment"]

0      i mentioned on facebook that i was struggling ...
1      bbc news - amazon boss jeff bezos rejects clai...
2      @microsoft why do i pay for word when it funct...
3      csgo matchmaking is so full of closet hacking,...
4      now the president is slapping americans in the...
                             ...
995    ⭐️ toronto is the arts and culture capital of ...
996    this is actually a good move tot bring more vi...
997    today sucked so it’s time to drink wine n play...
998    bought a fraction of microsoft today. small wins.
999    johnson & johnson to stop selling talc baby po...
Name: Comment, Length: 1000, dtype: object

In [5]:
def replace_text(text):

    text=re.sub(r"http\S+","",text) # replace all the urls starting with http or https with empty string
    # \S+ matches any non whitespace characters

    text=re.sub(r"[^a-z\s]","",text) # replace all elements 
    # \s matches a single whitespace character

    return text

df["Comment"]=df["Comment"].apply(replace_text)

In [6]:
df["Comment"]

0      i mentioned on facebook that i was struggling ...
1      bbc news  amazon boss jeff bezos rejects claim...
2      microsoft why do i pay for word when it functi...
3      csgo matchmaking is so full of closet hacking ...
4      now the president is slapping americans in the...
                             ...
995     toronto is the arts and culture capital of ca...
996    this is actually a good move tot bring more vi...
997    today sucked so its time to drink wine n play ...
998      bought a fraction of microsoft today small wins
999    johnson  johnson to stop selling talc baby pow...
Name: Comment, Length: 1000, dtype: object