In [29]:
import pandas as pd
import numpy as np

In [30]:
data=pd.read_csv("taxi_trip_pricing.csv")
df=pd.DataFrame(data)
df

     Trip_Distance_km Time_of_Day  ... Trip_Duration_Minutes  Trip_Price
0               19.35     Morning  ...                 53.82     36.2624
1               47.59   Afternoon  ...                 40.57         NaN
2               36.87     Evening  ...                 37.27     52.9032
3               30.33     Evening  ...                116.81     36.4698
4                 NaN     Evening  ...                 22.64     15.6180
..                ...         ...  ...                   ...         ...
995              5.49   Afternoon  ...                 58.39     34.4049
996             45.95       Night  ...                 61.96     62.1295
997              7.70     Morning  ...                 54.18     33.1236
998             47.56     Morning  ...                114.94     61.2090
999             22.85     Morning  ...                 29.69     45.4437

[1000 rows x 11 columns]

In [31]:
df.isna().sum()

Trip_Distance_km         50
Time_of_Day              50
Day_of_Week              50
Passenger_Count          50
Traffic_Conditions       50
Weather                  50
Base_Fare                50
Per_Km_Rate              50
Per_Minute_Rate          50
Trip_Duration_Minutes    50
Trip_Price               49
dtype: int64

In [32]:
df.dtypes

Trip_Distance_km         float64
Time_of_Day               object
Day_of_Week               object
Passenger_Count          float64
Traffic_Conditions        object
Weather                   object
Base_Fare                float64
Per_Km_Rate              float64
Per_Minute_Rate          float64
Trip_Duration_Minutes    float64
Trip_Price               float64
dtype: object

In [33]:
for i in list(df):

    if df[i].dtype=="object":

        df[i]=df[i].fillna(df[i].mode()[0])

    else:
        df[i]=df[i].fillna(df[i].mean())

In [34]:
df.isna().sum()

Trip_Distance_km         0
Time_of_Day              0
Day_of_Week              0
Passenger_Count          0
Traffic_Conditions       0
Weather                  0
Base_Fare                0
Per_Km_Rate              0
Per_Minute_Rate          0
Trip_Duration_Minutes    0
Trip_Price               0
dtype: int64

In [35]:
df_E=pd.get_dummies(df[["Time_of_Day","Day_of_Week","Traffic_Conditions","Weather"]],dtype=int)

In [36]:
df_E.dtypes

Time_of_Day_Afternoon        int64
Time_of_Day_Evening          int64
Time_of_Day_Morning          int64
Time_of_Day_Night            int64
Day_of_Week_Weekday          int64
Day_of_Week_Weekend          int64
Traffic_Conditions_High      int64
Traffic_Conditions_Low       int64
Traffic_Conditions_Medium    int64
Weather_Clear                int64
Weather_Rain                 int64
Weather_Snow                 int64
dtype: object

In [38]:
df_E.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Time_of_Day_Afternoon      1000 non-null   int64
 1   Time_of_Day_Evening        1000 non-null   int64
 2   Time_of_Day_Morning        1000 non-null   int64
 3   Time_of_Day_Night          1000 non-null   int64
 4   Day_of_Week_Weekday        1000 non-null   int64
 5   Day_of_Week_Weekend        1000 non-null   int64
 6   Traffic_Conditions_High    1000 non-null   int64
 7   Traffic_Conditions_Low     1000 non-null   int64
 8   Traffic_Conditions_Medium  1000 non-null   int64
 9   Weather_Clear              1000 non-null   int64
 10  Weather_Rain               1000 non-null   int64
 11  Weather_Snow               1000 non-null   int64
dtypes: int64(12)
memory usage: 93.9 KB

In [39]:
# combine both df and df_E

final_df=pd.concat([df,df_E],axis=1)
final_df

     Trip_Distance_km Time_of_Day  ... Weather_Rain  Weather_Snow
0           19.350000     Morning  ...            0             0
1           47.590000   Afternoon  ...            0             0
2           36.870000     Evening  ...            0             0
3           30.330000     Evening  ...            0             0
4           27.070547     Evening  ...            0             0
..                ...         ...  ...          ...           ...
995          5.490000   Afternoon  ...            0             0
996         45.950000       Night  ...            0             0
997          7.700000     Morning  ...            1             0
998         47.560000     Morning  ...            0             0
999         22.850000     Morning  ...            0             0

[1000 rows x 23 columns]

In [40]:
final_df=final_df.drop(columns=["Time_of_Day","Day_of_Week","Traffic_Conditions","Weather"],axis=1)
final_df

     Trip_Distance_km  Passenger_Count  ...  Weather_Rain  Weather_Snow
0           19.350000              3.0  ...             0             0
1           47.590000              1.0  ...             0             0
2           36.870000              1.0  ...             0             0
3           30.330000              4.0  ...             0             0
4           27.070547              3.0  ...             0             0
..                ...              ...  ...           ...           ...
995          5.490000              4.0  ...             0             0
996         45.950000              4.0  ...             0             0
997          7.700000              3.0  ...             1             0
998         47.560000              1.0  ...             0             0
999         22.850000              3.0  ...             0             0

[1000 rows x 19 columns]

In [42]:
Y=final_df["Trip_Price"]

In [44]:
final_df=final_df.drop(columns=["Trip_Price"],axis=1)
X=final_df
X

     Trip_Distance_km  Passenger_Count  ...  Weather_Rain  Weather_Snow
0           19.350000              3.0  ...             0             0
1           47.590000              1.0  ...             0             0
2           36.870000              1.0  ...             0             0
3           30.330000              4.0  ...             0             0
4           27.070547              3.0  ...             0             0
..                ...              ...  ...           ...           ...
995          5.490000              4.0  ...             0             0
996         45.950000              4.0  ...             0             0
997          7.700000              3.0  ...             1             0
998         47.560000              1.0  ...             0             0
999         22.850000              3.0  ...             0             0

[1000 rows x 18 columns]

In [45]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3)

In [46]:
from sklearn.preprocessing import StandardScaler

sc=StandardScaler()

X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [47]:
from sklearn.linear_model import LinearRegression

lr=LinearRegression()

lr=lr.fit(X_train,Y_train)

Y_pred=lr.predict(X_test)

In [48]:
from sklearn.metrics import mean_absolute_percentage_error,r2_score

print(f"Mean_Absolute_Percentag_Error = {mean_absolute_percentage_error(Y_test,Y_pred)}")

print(f"R2_Score = {r2_score(Y_test,Y_pred)}")

Mean_Absolute_Percentag_Error = 0.23609519702237525
R2_Score = 0.8805784313564888